- name: Run pre drush commands - {{ instance.name }}
  command: "{{ drush_path }} {{ instance.drush_profile | default('') }} {{ item }}"
  loop: '{{ instance.pre_drush_commands | default([]) }}'
  when: drush_path != ''

- name: Run pre commands - {{ instance.name }}
  become: "{{ item.become | default('false') }}"
  become_user: '{{ item.become_user | default(omit) }}'
  command: '{{ item.command }}'
  args:
    chdir: '{{ item.chdir | default(omit) }}'
  loop: '{{ instance.pre_commands | default([]) }}'
