- set_fact: sync_excludes="{{ instance.sync_excludes | default(project_sync_excludes)}}"

- name: Sync files from remote host - {{ instance.name }}
  command: rsync {{ project_sync_remote_rsync_options }} --exclude={{ sync_excludes | join(' --exclude=') | default('') }} {{ '-e "ssh -p ' + source_port|string + '" ' if source_port != '' else '' }}{{ instance.src_host }}:{{ instance.src_dir }} {{ instance.target_parent_dir }}/
  register: sync_result
  changed_when: sync_result.stdout_lines | length != 4
  when: instance.src_host is defined and instance.src_host != ''

- name: Sync files - {{ instance.name }}
  command: rsync {{ project_sync_local_rsync_options }} --exclude={{ sync_excludes | join(' --exclude=') | default('') }} {{ instance.src_dir }} {{ instance.target_parent_dir }}/
  register: sync_result
  changed_when: sync_result.stdout_lines | length != 4
  when: instance.src_host is not defined or instance.src_host == ''

- name: Set permissions to directories - {{ instance.name }}
  file:
    path: '{{ item.name }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    recurse: yes
  loop: '{{ instance.target_dirs_permission | default([]) }}'

#  synchronize:
#    mode: pull
#    src: '{{ instance.target_dir }}/'
#    dest: '{{ instance.src_dir }}'
#    dest_port: '{{ instance.src_port | default(omit) }}'
#    delete: yes
#    recursive: yes
#    archive: yes
#    rsync_timeout: 10
#    set_remote_user: no
#    verify_host: no
#  delegate_to: "{{ instance.src_host }}"
