- include_tasks: instance.yml
  tags: project-sync
  with_items: "{{ project_sync_instances | default([]) }}"
  loop_control:
    loop_var: instance
  when: >
    (project_sync_instance_name != '' and project_sync_instance_name == instance.name)
    or (project_sync_instance_name == ''
        and (project_sync_skip_replication or
          ((project_sync_run_all_master == True and project_sync_master and instance.run_on_sync_master is defined and instance.run_on_sync_master == True)
          or (project_sync_run_all_client == True and project_sync_client and instance.run_on_sync_client is defined and instance.run_on_sync_client == True))))
