- include: instance.yml
  tags: project-sync
  with_items: "{{ project_sync_instances | default([]) }}"
  loop_control:
    loop_var: instance
  when: >
    ((project_sync_instance_name is undefined)
      or (project_sync_instance_name is defined and instance.name == project_sync_instance_name))
    and ((not project_sync_master and not project_sync_client)
      or (project_sync_master and instance.run_on_sync_master is defined and instance.run_on_sync_master and project_sync_run_all_master)
      or (project_sync_client and instance.run_on_sync_client is defined and instance.run_on_sync_client and project_sync_run_all_client))
